### ISSUE TITLE
Пуллреквесты новых статей для дайджеста: в какую ветку

### ISSUE THREAD

**Issue by ctrlok** [ukrops/web#4]
Предлагаю тут обсудить в какую ветку делаем пул реквесты.

**Comment by Mykolaichenko** [comment]
Предлагаю сделать `dev` для дайджеста - бранчу `dev_digest`. 
В ней работать, добавлять ссылки, коментить, деклайнить и т.п. 
Перед датой релиза дайджеста мердж из `dev_digest` в основную ветку проекта.

**Comment by ctrlok** [comment]
Тут такая штука, что можно отмечать статьи как draft, если добавлять их в каталог [_drafts](https://github.com/ukrops/web/tree/gh-pages/_drafts)
Может так будет удобнее, чем несколько веток?

**Comment by ctrlok** [comment]
А релизом будет перенос из drafts в posts

**Comment by Mykolaichenko** [comment]
Так тоже можно в принципе, но мне не очень нравится идея работать в основной ветке проекта. Получится, что я буду засорять `git log` мастера, да и в истории `move` файла - не очень красиво. 
Мне кажется, что оптимальным решением в данном случае все же будет отдельная ветка для дайджеста, в которой будет осуществляться вся работа.
Когда все готово - открываем пул риквест с `dev_digest` в `master` и если все ок, то @ctrlok  мерджит.

**Comment by ctrlok** [comment]
Звучит ок :)

**Comment by Mykolaichenko** [comment]
@z0rc вчера спрашивал, как контрибьютить.

Если изменения не нужно апрувить (минорные правки): 
```
1) git pull https://github.com/ukrops/web.git
2) git checkout dev_digest 
3) ... change something ... 
4) git push origin dev_digest 
```

Если нужно апрувить (мажорные правки): 
```
1) fork 
2) git clone https://github.com/$username/web.git
3) git checkout dev_digest 
4) ... change something ...
5) git push origin dev_digest
6) open pull request to dev_digest  
```

**Comment by z0rc** [comment]
Ясно спасибо, но для первого варинта я должен быть в статусе Collaborator (написал этот комментарий, чтобы проверить).

Edit: таки не Collaborator.
